name: Dockerfile
on: 
  pull_request:
    types: [opened,edited,synchronize,reopened]
  push: 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/remote-named-dockerfile
